jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'

#metadata:
#    auto_detection: false
#    directories:
#        RegistrationDto:
#            namespace_prefix: "App\\Infrastructure\\Entity"
#            path: "%kernel.project_dir%/Resources/Serializer/User.yml"

# возможность пользоватся Builder
# JMS\Serializer\SerializerBuilder::create()->build()
services:
    JMS\Serializer\SerializerBuilder:
        autowire: true




