index:
    path: /test
    controller: App\Infrastructure\Controller\TestController::test
registration:
    path: /registration
    controller: App\Infrastructure\Controller\Registration\RegistrationController::registration