App\Domain\Dto\RegistrationRequest:
  constraints:
    - Callback: validate
  properties:
    login:
      - NotBlank: {message: 'нет поле "login"'}
    password:
      - NotBlank: { message: 'нет поле "password"' }
